# Generated by Django 4.0.4 on 2022-05-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='cep',
            field=models.CharField(default=35565, max_length=20, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusuario',
            name='complemento',
            field=models.CharField(default=1, max_length=30, verbose_name='Complemento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusuario',
            name='estado',
            field=models.CharField(default=1, max_length=20, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusuario',
            name='municipio',
            field=models.CharField(default=1, max_length=20, verbose_name='Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusuario',
            name='numero',
            field=models.CharField(default=1, max_length=5, verbose_name='Numero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusuario',
            name='pais',
            field=models.CharField(default=1, max_length=20, verbose_name='Pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusuario',
            name='pis',
            field=models.IntegerField(default=1, verbose_name='Pis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusuario',
            name='rua',
            field=models.CharField(default=1, max_length=20, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
