# Generated by Django 4.0.4 on 2022-05-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customusuario_cep_customusuario_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='pis',
            field=models.CharField(max_length=30, verbose_name='Pis'),
        ),
    ]
